### PR TITLE
Adds Sketch file for Q logo.

### PR DESCRIPTION
**Pull request by ashfurrow**
It's all vector-based so it can be arbitrarily rescaled. Here's a sample:

q logo

### CODE REVIEW

**Comment by ashfurrow** [comment]
I'd like to do the full logo but need the font first. Tried the usual suspects but none looked like a match.

**Comment by modocache** [comment]
I'll look through my files to see if I can find the font. If not I'll try and get in touch with the original designer. :+1:

**Comment by ashfurrow** [comment]
Cool cool! No worries, I've got what I need for my presentation. Thanks for the tips!

**Comment by paulyoung** [comment]
Hey @modocache, remember that time I told you I thought the Quick logo looked like a snail? :snail: :smile:

**Comment by modocache** [comment]
Oh great, now I can't unsee it again! :joy:

**Pull request merged**
